### PR TITLE
Fix Deleted Space Bug

### LINKED ISSUE #1525: Crash "TypeError: Cannot read property 'ingest' of null" when Space is deleted
Repro is with a [macOS nightly build](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-6a288f1c.0/macos/Brim.dmg) based on Brim commit 6a288f1.

To repro, I import a small pcap [hello.pcapng.gz](https://github.com/brimsec/brim/files/6185117/hello.pcapng.gz) (after uncompressing), then delete the Space that was created.

https://user-images.githubusercontent.com/5934157/112054706-1fdabb00-8b13-11eb-9a60-a0665c6af800.mp4

The stack dump as text:

```
TypeError: Cannot read property 'ingest' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'ingest' of null
    at /Applications/Brim.app/Contents/Resources/app/dist/src/js/state/Ingest/index.js:15:16
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:76:25
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:36:25
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:90:33
    at Object.current (/Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:36:25)
    at Subscription.checkForUpdates [as onStateChange] (/Applications/Brim.app/Contents/Resources/app/node_modules/react-redux/lib/hooks/useSelector.js:59:47)
    at Subscription.handleChangeWrapper (/Applications/Brim.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:103:12)
    at /Applications/Brim.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:29:20
    at batchedUpdates$1 (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
    at Object.notify (/Applications/Brim.app/Contents/Resources/app/node_modules/react-redux/lib/utils/Subscription.js:25:7)


    at /Applications/Brim.app/Contents/Resources/app/dist/src/js/state/Ingest/index.js:15:16
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:76:25
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:36:25
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:90:33
    at /Applications/Brim.app/Contents/Resources/app/node_modules/reselect/lib/index.js:36:25
    at useSelectorWithStoreAndSubscription (/Applications/Brim.app/Contents/Resources/app/node_modules/react-redux/lib/hooks/useSelector.js:39:23)
    at useSelector (/Applications/Brim.app/Contents/Resources/app/node_modules/react-redux/lib/hooks/useSelector.js:115:12)
    at useIngestWatch (/Applications/Brim.app/Contents/Resources/app/dist/app/search/hooks/use-ingest-watch.js:49:46)
    at SearchHome (/Applications/Brim.app/Contents/Resources/app/dist/app/search/home.js:90:34)
    at renderWithHooks (/Applications/Brim.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:14803:18)
```

### PR DESCRIPTION
**Pull request by jameskerr**
Deleting a space that as active in the tab would cause a crash. Now it redirects to the import page.

I added an integration test to keep us from regressing. 

fixes #1525

### CODE REVIEW

File: itest/lib/createTestBrim.ts [hunk 1]
```diff
@@ -20,6 +22,14 @@ export default (name: string) => {
   })
 
   return {
+    $(locator: Locator) {
```
Comment (mason-fish) [inline itest/lib/createTestBrim.ts:25]: 👍

**Review by mason-fish — APPROVED** [review]
Nice catch
