### PR TITLE
JSON Config Validation Bug

### LINKED ISSUE #792: setting defaultTypes.json as JSON schema causes TypeError
When I follow instructions at https://github.com/brimsec/brim/wiki/Zeek-JSON-Import to set a JSON schema, the following is logged to developer tools console:
```
TypeError: Invalid attempt to destructure non-iterable instance
    at _nonIterableRest (/Applications/Brim.app/Contents/Resources/app/dist/js/brim/form.js:10)
    at _slicedToArray (/Applications/Brim.app/Contents/Resources/app/dist/js/brim/form.js:8)
    at _callee$ (/Applications/Brim.app/Contents/Resources/app/dist/js/brim/form.js:57)
    at tryCatch (/Applications/Brim.app/Contents/Resources/app/node_modules/regenerator-runtime/runtime.js:45)
    at Generator.invoke [as _invoke] (/Applications/Brim.app/Contents/Resources/app/node_modules/regenerator-runtime/runtime.js:271)
    at Generator.prototype.<computed> [as next] (/Applications/Brim.app/Contents/Resources/app/node_modules/regenerator-runtime/runtime.js:97)
    at asyncGeneratorStep (/Applications/Brim.app/Contents/Resources/app/dist/js/brim/form.js:16)
    at _next (/Applications/Brim.app/Contents/Resources/app/dist/js/brim/form.js:18)
```
Note that I tried this on an installed release package (`node scripts/release --darwin`) to work around #791 .

The file I wanted to upload to this is `config/defaultTypes.json`. Commit hash is 416f14a52bc2da9e423e6fac202bf0a4fd879cee.

### PR DESCRIPTION
**Pull request by jameskerr**
In the happy case when the file existed and was json, the form
check returned undefined instead of an array. This pr fixes that
and adds a better error message for the future.

Fixes #792

### CODE REVIEW

File: src/js/components/Preferences/usePreferencesForm.js [hunk 1]
```diff
@@ -48,6 +48,7 @@ export default function usePreferencesForm(): FormConfig {
           .file(path)
           .read()
           .then((text) => JSON.parse(text))
+          .then(() => [true, ""])
```
Comment (jameskerr) [inline src/js/components/Preferences/usePreferencesForm.js:51]: The bug was caused by the absence of this line.
