### PR TITLE
fix: Store spaceId in request handler state

### LINKED ISSUE #778: Space not being deleted when quitting Brim during pcap import
Repro is with Brim commit `718af8a` talking to `zqd` commit `8301413`.

[Repro.mp4.zip](https://github.com/brimsec/brim/files/4629467/Repro.mp4.zip)

When I quit Brim, I can see the following message in my NPM window:

```
08:38:14.794 › [f5b7b022f0]:  Confirming Unload...
08:38:16.227 › [f5b7b022f0]:  Unloading
08:38:16.228 › [f5b7b022f0]:  starting delete for wrccdc.2018-03-24.101533000000000.pcap.brim
08:38:16.231 › [f5b7b022f0]:  Unable to delete space: wrccdc.2018-03-24.101533000000000.pcap.brim, reason: [object Object]
08:38:16.232 › [f5b7b022f0]:  Saving window state
08:38:16.654 › [f5b7b022f0]:  Window state saved
08:38:16.656 › [f5b7b022f0]:  Destroying window
```

### PR DESCRIPTION
**Pull request by jameskerr**
fixes #778 

We save the names of all spaces that are currently ingesting. This way we can clean up the spaces if they decided to quit the app.

Instead of saving the names, save the ids.

### CODE REVIEW

File: src/js/flows/confirmUnload.js [hunk 1]
```diff
@@ -3,14 +3,18 @@ import {isEmpty} from "lodash"
 
 import type {Thunk} from "../state/types"
 import Handlers from "../state/Handlers"
+import Spaces from "../state/Spaces"
+import Tab from "../state/Tab"
 import showIngestWarning from "./showIngestWarning"
 
 export default (): Thunk => (dispatch, getState) => {
-  let spaces = Handlers.getIngestSpaceNames(getState())
+  let spaceIds = Handlers.getIngestSpaceIds(getState())
```
Comment (mattnibs) [inline src/js/flows/confirmUnload.js:11]: I was thinking this was the best way to solve this- store id and do join on state.Spaces to get name. Good to know>

**Comment by mattnibs** [comment]
I get this error when I try to close the tab during ingest now:
```
Uncaught TypeError: Cannot read property 'name' of undefined
    at /Users/nibs/Code/brim/dist/js/flows/confirmUnload.js:30
    at Array.map (<anonymous>)
    at /Users/nibs/Code/brim/dist/js/flows/confirmUnload.js:29
    at /Users/nibs/Code/brim/node_modules/redux-thunk/lib/index.js:11
    at dispatch (/Users/nibs/Code/brim/node_modules/redux/lib/redux.js:644)
    at /Users/nibs/Code/brim/dist/js/flows/closeWindow.js:24
    at /Users/nibs/Code/brim/node_modules/redux-thunk/lib/index.js:11
    at EventEmitter.<anonymous> (/Users/nibs/Code/brim/dist/js/initializers/initSearch.js:96)
    at EventEmitter.emit (events.js:203)
    at Object.onMessage (init.ts:50)
```

File: src/js/flows/confirmUnload.js (hunk 1 above)
Comment (jameskerr) [reply src/js/flows/confirmUnload.js:11]: Yes, we could provide a function to make that more ergonomic though.

**Comment by jameskerr** [comment]
Thanks for testing @mattnibs. I'll make a check for undefined.
