### PR TITLE
fix modal close

### LINKED ISSUE #1080: Provide UI indication for newConnection status check
On the newConnection modal, after hitting 'Connect', we keep the modal open until the status check succeeds (and if it doesn't we display errors within the modal), but during this status check there is no indication that anything is happening. Let's add a spinner next to the connect button while we wait for the response.

### PR DESCRIPTION
**Pull request by mason-fish**
fixes #1080 

I added some more context in ticket ^^

brim

### CODE REVIEW

File: src/js/components/NewConnectionModal.tsx [hunk 1]
```diff
@@ -110,22 +111,25 @@ export default function NewConnectionModal() {
...
       }
     },
-    [f, config]
+    [f, config, setIsFetching]
   )
 
   const buttons = [
     {label: "Cancel", click: (closeModal) => closeModal()},
-    {label: "Connect", click: onSubmit}
+    {label: "Connect", click: onSubmit, showSpinner: isFetching}
```
Comment (jameskerr) [inline src/js/components/NewConnectionModal.tsx:132]: Instead of adding a `showSpinner` option, why not add a more generic "icon" option where you could inject the MacSpinner.

This does make me think about buttons with a loading state. I'd like to design a first-class "loading" state into the buttons. I always feel comforted as a user when I see those in other apps.

File: src/js/components/NewConnectionModal.tsx [hunk 2]
```diff
@@ -110,22 +111,25 @@ export default function NewConnectionModal() {
...
+        } finally {
+          setIsFetching(false)
         }
         closeModal()
       } else {
         setErrors(form.getErrors())
       }
     },
-    [f, config]
+    [f, config, setIsFetching]
```
Comment (jameskerr) [inline src/js/components/NewConnectionModal.tsx:127]: I don't think setIsFetching is necessary to include the deps here. I think the setters won't get stale like the values will.

File: src/js/components/ModalBox/ModalBox.tsx [hunk 3]
```diff
@@ -34,7 +34,7 @@ export default function ModalBox({name, children, ...props}: ModalBoxProps) {
   }
 
   return (
-    <Animate show={active === name} enter={enter} exit="reverse">
+    <Animate show={active === name} enter={enter}>
```
Comment (jameskerr) [inline src/js/components/ModalBox/ModalBox.tsx:37]: Yes, a faster "exiting" state is nice.

**Comment by jameskerr** [comment]
Here's a design I like for the loading state of a button: https://www.sketch.com/s/4b2957a2-910e-403c-9fda-617de055c061/a/OEY3dp#Inspector

image

**Review by jameskerr — CHANGES_REQUESTED** [review]
A few suggestions.

**Review by jameskerr — APPROVED** [review]
Very cool! Thanks Mason
