### PR TITLE
Fix double click bug

### LINKED ISSUE #966: Double clicking on two different rows, acts like double clicking on the second row
**Describe the bug**
Quickly clicking two different logs will trigger the "onDoubleClick" handler for the latter log. 

**Expected behavior**
I'd expect that you'd only get the detail view by clicking twice, quickly on the same log line.

### PR DESCRIPTION
**Pull request by mason-fish**
fixes #966 

Track previously selected index, and compare on double click

Signed-off-by: Mason Fish <mason@looky.cloud>

### CODE REVIEW

File: src/js/components/LogRow.js [hunk 1]
```diff
@@ -19,51 +20,69 @@ type Props = {
...
+
+export default memo<Props>(LogRow, (prevProps: Props, nextProps: Props) => {
+  return !(
+    !Log.isSame(prevProps.log, nextProps.log) ||
+    !isEqual(prevProps.columns, nextProps.columns) ||
+    prevProps.highlight !== nextProps.highlight ||
+    prevProps.dimens.rowWidth !== nextProps.dimens.rowWidth ||
+    prevProps.timeZone !== nextProps.timeZone ||
+    prevProps.timeFormat !== nextProps.timeFormat
+  )
```
Comment (jameskerr) [inline src/js/components/LogRow.js:87]: How about inverting this to avoid the double negatives?

```js
return Log.isSame(prevProps.log, nextProps.log) &&
  isEqual(prevProps.columns, nextProps.columns) &&
  prevProps.highlight === nextProps.highlight &&
  prevProps.dimens.rowWidth === nextProps.dimens.rowWidth &&
  prevProps.timeZone === nextProps.timeZone &&
  prevProps.timeFormat === nextProps.timeFormat
```

Comment (jameskerr) [reply src/js/components/LogRow.js:87]: I'm glad the inverted the API, I think it makes more sense to say, "use the memo'ed version when this condition is true."

File: src/js/components/LogRow.js [hunk 2]
```diff
@@ -19,51 +20,69 @@ type Props = {
...
+        />
+      )
+    }
+    if (dimens.rowWidth !== "auto") {
+      return (
+        <div
+          className="log-cell"
+          key={key}
+          style={{width}}
+          onClick={handleClick}
```
Comment (jameskerr) [inline src/js/components/LogRow.js:62]: I don't see why the log cell needs to have the click handler? Is that intentional?

File: src/js/components/LogRow.js [hunk 3]
```diff
@@ -19,51 +20,69 @@ type Props = {
...
+      className={classNames("log-row", {highlight, even: index % 2 === 0})}
+      style={Styler.row(dimens)}
+      onClick={handleClick}
+    >
+      {columns.getVisible().map(renderCell)}
+    </div>
+  )
 }
+
+export default memo<Props>(LogRow, (prevProps: Props, nextProps: Props) => {
```
Comment (jameskerr) [inline src/js/components/LogRow.js:79]: Thanks for doing this. It looks simpler that I'd thought it would be.

File: src/js/components/LogRow.js (hunk 2 above)
Comment (mason-fish) [reply src/js/components/LogRow.js:62]: Ah shoot, no this is a mistake. I put it here at first and realized it belonged on the whole row but forgot to remove this. Nice catch

File: src/js/components/LogRow.js (hunk 1 above)
Comment (mason-fish) [reply src/js/components/LogRow.js:87]: I had the same thought actually. Glad you agree, will change

**Comment by jameskerr** [comment]
👍 I see what you mean. We needed the click event now. Thanks for fixing.
