### PR TITLE
fix: move installer requires only to where needed

### LINKED ISSUE #724: scripts/release fails on windows because electron-installer-{debian,redhat} are unconditionally required
I was testing the release workflow for my work on #634 and discovered the windows release job fails with:

```
Error: Cannot find module 'electron-installer-debian'
Require stack:
- D:\a\brim\brim\scripts\release\install.js
- D:\a\brim\brim\scripts\release\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\a\brim\brim\scripts\release\install.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\a\brim\brim\scripts\release\index.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\brim\\brim\\scripts\\release\\install.js',
    'D:\\a\\brim\\brim\\scripts\\release\\index.js'
  ]
}
```
https://github.com/brimsec/brim/runs/637254118?check_suite_focus=true

This happens because the electron installers for linux are in `optionalDependencies` (and unavailable on windows) but the requires of them in `scripts/release/install.js` are unconditional:

https://github.com/brimsec/brim/blob/d0db49d7dc65b8ad12b946dcc4997029eb164acd/scripts/release/install.js#L5

### PR DESCRIPTION
**Pull request by mikesbrown**
Fixes #724.

Test release at https://github.com/brimsec/brim/releases/tag/v0.9.0-dev

Release checks

- https://github.com/brimsec/brim/actions/runs/93379314
- https://github.com/brimsec/brim/actions/runs/93379306
- https://github.com/brimsec/brim/actions/runs/93379318

### CODE REVIEW

File: scripts/release/install.js [hunk 1]
```diff
@@ -90,6 +89,7 @@ module.exports = {
 
   redhat: function() {
     console.log("Building rpm package installer")
+    const installerRedhat = require("electron-installer-redhat")
```
Comment (mattnibs) [inline scripts/release/install.js:92]: Perhaps a comment here (and above) as to why these need to required here?

Comment (mattnibs) [reply scripts/release/install.js:92]: I could easily see myself moving this back up top, not knowing why it was here to begin w/.

Comment (mikesbrown) [reply scripts/release/install.js:98]: Yep; done
